### ISSUE TITLE
RuntimeError: GlooDeviceFactory::makeUVDevice(): interface or hostname can't be empty on mango rvc

### ISSUE THREAD

**Issue by Accy587** [maxrmorrison/torchcrepe#30]
Traceback (most recent call last):
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "C:\Users\me\Desktop\rvc\train_nsf_sim_cache_sid_load_pretrain.py", line 100, in run
    dist.init_process_group(
  File "C:\Users\me\Desktop\rvc\runtime\lib\site-packages\torch\distributed\distributed_c10d.py", line 895, in init_process_group
    default_pg = _new_process_group_helper(
  File "C:\Users\me\Desktop\rvc\runtime\lib\site-packages\torch\distributed\distributed_c10d.py", line 994, in _new_process_group_helper
    backend_class = ProcessGroupGloo(backend_prefix_store, group_rank, group_size, timeout=timeout)
RuntimeError: GlooDeviceFactory::makeUVDevice(): interface or hostname can't be empty

and i did run pip install torchcrepe beforehand

**Comment by maxrmorrison** [comment]
Given your stack trace, this does not appear to be a `torchcrepe` issue.
